### ISSUE TITLE
version 1.2.1 no definition for MultiStackNaviagor

### ISSUE THREAD

**Issue by wman1980** [tunjid/Android-Extensions#118]
Hey @tunjid,

with version 1.2.1 I'll get an error:

`Unresolved reference: MultiStackNavigator`

with version 1.2.0 it works ...

**Comment by tunjid** [comment]
@wman1980 hey so I noticed it this week too! It turns out that because jcenter is sunsetting, they did not accept the latest 1.2.1 artifact for publish. I'm currently in the process of migrating to maven central, the hard parts been done:

https://issues.sonatype.org/browse/OSSRH-67123?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=1041053

I just need to set up my CI to finally publish. Should be available by EOD today at the earliest or hopefully end of the weekend at the latest.

**Comment by tunjid** [comment]
@wman1980 navigation 1.2.1 is now available on maven central
