### ISSUE TITLE
Bug: bad transformation on list when going back to it

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tunjid/Android-Extensions#2]
Check the video that's attached:

[device-2019-12-07-140719.zip](https://github.com/tunjid/Android-Extensions/files/3935038/device-2019-12-07-140719.zip)

**Comment by tunjid** [comment]
@AndroidDeveloperLB thanks for pointing out the issue! It happens when the shared element transition starts before the recyclerview scrolls to make sure the item is in the proper place. I should fixe this by postponing the transition, I just haven't gotten around to it yet.

**Comment by AndroidDeveloperLB** [comment]
Please show in code why it occurs, and how you fix it.
I want to see if I can learn from it.

**Comment by tunjid** [comment]
@AndroidDeveloperLB it is fixed in the linked PR. Since there is a shared element transition between fragments, in `onCreateView` I call `postponeEnterTransition()` to make sure the image has been loaded with `Picasso` before the transition runs.

Also, since the user may be returning to an image that is offscreen, I use `scrollToPosition()` to make sure the image shows fully on the screen for animating.

Sometimes, the image will have loaded before the RecyclerView has scrolled (Image was cached). To fix this, I need to wait till the `RecyclerView` has scrolled before starting the transition. The fix is to call `view?.doOnLayout` to start the transition after the `RecyclerView` has scrolled.

Thanks again for pointing out the bug!

```
    override fun onDoggoImageLoaded(doggo: Doggo) {
        if (doggo == Doggo.transitionDoggo) view?.doOnLayout { startPostponedEnterTransition() }
    }
```

**Comment by AndroidDeveloperLB** [comment]
And this fixed it? can you please show a video?

**Comment by tunjid** [comment]
@AndroidDeveloperLB sorry I missed this, yes it did fix it. I can't quite record a video right now, but you can run it to verify.

**Comment by AndroidDeveloperLB** [comment]
OK tried now.
Seems to still has an issue:
The RecyclerView scrolls while I'm on the new screen. 

See attached video:
[2020-02-12_23-30-34.zip](https://github.com/tunjid/Android-Extensions/files/4195116/2020-02-12_23-30-34.zip)
